### PR TITLE
Docs: Various additions/fixes

### LINKED ISSUE #301: Update example module name in smart cell docs
More of a reminder to myself to submit a PR later :)

Kino module docs recommend not using `Kino.` prefix for custom kinos: https://hexdocs.pm/kino/Kino.html#module-custom-kinos

Kino smart cell docs use `Kino.SmartCell.Custom` -- should rename to `CustomSmartCell` or similar.

### PR DESCRIPTION
**Pull request by zachallaun**
Spent some time reading through the Kino docs this morning and came across a few things I thought could be improved. 🙂 

Will close #301.

### CODE REVIEW

File: lib/kino/smart_cell.ex [hunk 1]
```diff
@@ -24,7 +24,7 @@ defmodule Kino.SmartCell do
 
   Here is an outline of a custom module
 
-      defmodule Kino.SmartCell.Custom do
+      defmodule KinoDocs.SmartCell.Custom do
```
Comment (jonatanklosko) [inline lib/kino/smart_cell.ex:27]: This would be closest to how we've been calling them in `kino_*` projects :D

```suggestion
      defmodule KinoDocs.CustomCell do
```

File: lib/kino.ex [hunk 2]
```diff
@@ -538,6 +561,20 @@ defmodule Kino do
...
+        Kino.Input.text("Input")
+        |> Kino.render()
+        |> Kino.Input.read()
+
+      if text == "" do
+        Kino.interrupt!(:error, "Input required")
+      end
+
+      # This will not be run if the `interrupt!` is called above
+      Kino.Markdown.new("**You entered:** \#{text}")
```
Comment (jonatanklosko) [inline lib/kino.ex:577]: Let's use `~S"""` and not worry about escaping

```suggestion
      Kino.Markdown.new("**You entered:** #{text}")
```

**Review by jonatanklosko — COMMENTED** [review]
Thanks a lot, a few nitpicks and we can ship it!

**Comment by zachallaun** [comment]
Fixed!

**Review by jonatanklosko — APPROVED** [review]
