### PR TITLE
Fix code with interpolation in remote execution smart cell

### LINKED ISSUE #365: Bug happening when running remote execution smart cell
Running this code works:

CleanShot 2023-11-14 at 16 02 21

But running that doesn't work:

CleanShot 2023-11-14 at 16 04 34

Here's the code generated by the smart cell, when the code doesn't work:

```elixir
require Kino.RPC
node = String.to_atom(System.fetch_env!("LB_TEAMS_PROD_NODE"))
Node.set_cookie(node, String.to_atom(System.fetch_env!("LB_TEAMS_PROD_COOKIE")))

Kino.RPC.eval_string(
  node,
  """
  Hub.Orgs.Org.changeset(org, %{name: "#{org.name}"})
  |> Hub.Repo.update()
  """,
  file: __ENV__.file
)
```

That said, when the bug happens, even I run the generated code by the smart cell, when the code worked, now it doesn't:

CleanShot 2023-11-14 at 16 06 26

### PR DESCRIPTION
**Pull request by jonatanklosko**
Closes #365.

### CODE REVIEW

File: lib/kino/rpc.ex [hunk 1]
```diff
@@ -20,10 +20,18 @@ defmodule Kino.RPC do
...
-    unless is_binary(string) do
-      raise ArgumentError,
-            "Kino.RPC.eval_string/3 expects a string literal as the second argument"
-    end
+    string =
+      case string do
+        string when is_binary(string) ->
+          string
+
+        {sigil, _, [{:<<>>, _, [string]}, []]} when sigil in [:sigil_s, :sigil_S] ->
```
Comment (jonatanklosko) [inline lib/kino/rpc.ex:28]: @josevalim please double-check :)

File: lib/kino/rpc.ex [hunk 2]
```diff
@@ -20,10 +20,18 @@ defmodule Kino.RPC do
   See `Code.eval_string/3` for available `opts`.
   """
   defmacro eval_string(node, string, opts \\ []) do
-    unless is_binary(string) do
-      raise ArgumentError,
-            "Kino.RPC.eval_string/3 expects a string literal as the second argument"
-    end
+    string =
+      case string do
```
Comment (josevalim) [inline lib/kino/rpc.ex:24]: Maybe call `Macro.expand(string, __CALLER__)` and check if it returns a string?

**Review by josevalim — APPROVED** [review]
